version: '3'

networks:
  # enable connection with Traefik
  # 啟用與Traefik的連接
  traefik:
    external: true
  # network for the app
  # 應用程式的聯播網
  backend:

services:

  wordpress:
    container_name: wordpress
    build:
      # call the Dockerfile in ./wordpress
      context: ./wordpress
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    environment:
      # Connect WordPrerss to the database
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # save the content of WordPress an enable local modifications
      - ./wordpress/data:/var/www/html
    networks:
      - traefik
      - backend
    depends_on:
        - db
        - redis
    labels:
      # The labels are usefull for Traefik only
      # 標籤僅適用於Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Get the routes from http
      # 從http獲取路由
      - "traefik.http.routers.wordpresscp.rule=Host(`infowize.com`)"
      - "traefik.http.routers.wordpresscp.entrypoints=web"
      # Redirect these routes to https
      # 將這些路由重定向到https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpresscp.middlewares=redirect-to-https@docker"
      # Get the routes from https
      # 從https獲取路由
      - "traefik.http.routers.wordpresscp-secured.rule=Host(`infowize.com`)"
      - "traefik.http.routers.wordpresscp-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      # 通過http挑戰應用強化
      - "traefik.http.routers.wordpresscp-secured.tls=true"
      - "traefik.http.routers.wordpresscp-secured.tls.certresolver=myhttpchallenge"

  db:
    # this is the database used by Wordpress
    image: mariadb:10.1.44
    container_name: wordpress_db
    restart: always
    ports:
        - '3306:3306'
    environment:
      # Connect WordPrerss to the database
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      # Persist the database on disk
      - ./db:/var/lib/mysql
    networks:
      - backend


  redis:
    image: redis:latest
    container_name: wordpress_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    # launch Redis in cache mode with :
    #  - max memory up to 50% of your RAM if needed (--maxmemory 512mb)
    #  - 如果需要，最大內存最多為RAM的50％（-最大內存512mb）
    #  - deleting oldest data when max memory is reached (--maxmemory-policy allkeys-lru)
    entrypoint: redis-server --maxmemory 512mb -maxmemory-policy allkeys-lru
    